### ISSUE TITLE
Running TOBIAS BINDetect got an error

### ISSUE THREAD

**Issue by 2961461560** [loosolab/TOBIAS#22] opened 2020-07-16 12:52 UTC
Hi, I runned TOBIAS command which is the same with the example's. The first two comands, TOBIAS ATACorrect, FootprintScores, were successfully performed, but I got an error information when the third command was runned, 'TOBIAS BINDetect --motifs test_data/motifs.jaspar --signals test_data/Bcell_footprints.bw test_data/Tcell_footprints.bw --genome test_data/genome.fa.gz --peaks test_data/merged_peaks_annotated.bed --peak_header test_data/merged_peaks_annotated_header.txt --outdir BINDetect_output --cond_names Bcell Tcell'.
The error information:
Exception ignored in: <function Image.__del__ at 0x2ac061a644d0>
Traceback (most recent call last):
  File "/public/home/whli/anaconda3/envs/TOBIAS_ENV/lib/python3.7/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread Aborted (core dumped)

**Comment by msbentsen** [comment] 2020-07-16 13:02
Hi,

I have not seen that error before and I cannot reproduce it on my system. Could you give me some more information about what system you are on (mac/linux)?

Also, could you give me the output of `pip freeze` and `TOBIAS --version`? Thanks!

**Comment by 2961461560** [comment] 2020-07-16 13:12
My system is Liunx.


adjustText==0.7.3
appdirs==1.4.4
biopython @ file:///home/conda/feedstock_root/build_artifacts/biopython_1592943109796/work
boltons==20.2.0
boto3 @ file:///home/conda/feedstock_root/build_artifacts/boto3_1594848170328/work
botocore @ file:///home/conda/feedstock_root/build_artifacts/botocore_1594842816421/work
brotlipy==0.7.0
BucketCache==0.12.1
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorama==0.4.3
configparser==5.0.0
configs==3.0.3
cryptography==2.9.2
cycler==0.10.0
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1594253470382/work
decorator==4.4.2
diskcache==4.1.0
docutils==0.15.2
future==0.18.2
genomepy==0.8.3
gimmemotifs==0.14.4
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
Jinja2==2.11.2
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1593624380152/work
kiwisolver==1.2.0
Logbook==1.5.3
logomaker==0.8
MarkupSafe==1.1.1
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-base_1594091695977/work
MOODS-python==1.9.4.1
norns==0.1.5
nose==1.3.7
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1591485215893/work
olefile==0.46
pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1592421991297/work
patsy==0.5.1
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1594213010297/work
psutil==5.7.2
pybedtools==0.8.1
pyBigWig==0.3.17
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pyfaidx==0.5.9
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyPDF2==1.26.0
pysam==0.16.0.1
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
reportlab==3.5.44
Represent==1.6.0
requests==2.24.0
s3transfer==0.3.3
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1589920855303/work
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1593253469108/work
seaborn==0.10.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
sklearn-contrib-lightning==0.5.0
statsmodels==0.11.1
svist4get==1.2.22
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
tobias==0.11.3
tornado==6.0.4
tqdm==4.47.0
urllib3==1.25.9
Wand @ file:///home/conda/feedstock_root/build_artifacts/wand_1591809393263/work
xdg==4.0.1
xgboost==1.1.1
XlsxWriter @ file:///home/conda/feedstock_root/build_artifacts/xlsxwriter_1590799523302/work
xxhash==1.4.4



and TOBIAS version is&nbsp;0.11.3


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "loosolab/TOBIAS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 晚上9:02
收件人:&nbsp;"loosolab/TOBIAS"<TOBIAS@noreply.github.com&gt;;
抄送:&nbsp;"珍珠港的日出"<2961461560@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [loosolab/TOBIAS] Running TOBIAS BINDetect got an error (#22)





 
Hi,
 
I have not seen that error before and I cannot reproduce it on my system. Could you give me some more information about what system you are on (mac/linux)?
 
Also, could you give me the output of pip freeze and TOBIAS --version? Thanks!

**Comment by 2961461560** [comment] 2020-07-16 13:24
and I used these command to install TOBIAS.
git clone https://github.com/loosolab/TOBIAS.git
cd TOBIAS
conda env create -f tobias_env.yaml
conda activate TOBIAS_ENV
pip install tobias

**Comment by 2961461560** [comment] 2020-07-16 14:01
I only can install tobias by pip, and not by conda, `conda install tobias -c bioconda`, due to `UnsatisfiableError: The following specifications were found to be incompatible with each other`, even though using Python of different version, such as 3.6, 3.7, 3.8

**Comment by msbentsen** [comment] 2020-07-17 06:27
Hi, thank you for the information. I pushed some minor changes to a separate branch, so could you try to install using:
`pip install git+git://github.com/loosolab/TOBIAS@tkinter_error`

The `TOBIAS --version` command should read `0.11.4-b` after install. I could still not reproduce your exact error, but from other issues I think this might solve it. Please let me know if it works out with the new version!

**Comment by 2961461560** [comment] 2020-07-20 07:15
Hi, thank you very much. It is can be performed successfully now.

**Comment by msbentsen** [comment] 2020-07-20 11:46
Great, thank you for the feedback! Please install `tobias 0.11.4` from pypi, as I also made fixes to a few other tools. I am closing this, but let me know if you have any further issues.

**Closed by msbentsen** 2020-07-20 11:46 UTC

**Comment by 2961461560** [comment] 2020-07-23 02:56
Hi, I'am so embarrassed that I fell into some other errors when performed `TOBIAS BINDetect`  using my own data.
`[ERROR1]	Input region chr04	35502391	35502694 is beyond chromosome boundaries (chr04: 35502694)`
`[ERROR2]	Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.`

I'am now using `tobias 0.11.4`. the first error, I know what the reason is and you may need to add catching exception, but I don't know what the cause is for ERROR2.
I can run successfully your test data with the command below, `TOBIAS BINDetect --motifs test_data/motifs.jaspar --signals test_data/Tcell_day{1,2,3}_footprints.bw --genome test_data/genome.fa.gz --peaks test_data/merged_peaks_annotated.bed --peak_header test_data/merged_peaks_annotated_header.txt --outdir BINDetect_Tcell_output --time-series`, but my own data, ten time-series files, can't be performed using the command like your's because of the errors above.

**Comment by 2961461560** [comment] 2020-07-23 03:04
Hi, I'am so embarrassed that I fell into some other errors when performed TOBIAS BINDetect using my own data.
`[ERROR1] Input region chr04 35502391 35502694 is beyond chromosome boundaries (chr04: 35502694)`
`[ERROR2] Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.`

I'am now using tobias 0.11.4. the first error, I know what the reason is and you may need to add catching exception, but I don't know what the cause is for ERROR2.
I can run the command below with your test data, successfully, `TOBIAS BINDetect --motifs test_data/motifs.jaspar --signals test_data/Tcell_day{1,2,3}_footprints.bw --genome test_data/genome.fa.gz --peaks test_data/merged_peaks_annotated.bed --peak_header test_data/merged_peaks_annotated_header.txt --outdir BINDetect_Tcell_output --time-series`, but as for my own data, ten time-series files, it can't be performed using the command like your's because of the errors above.

**Comment by msbentsen** [comment] 2020-07-23 08:36
Hi, sorry ERROR1 is a bug from my side - the boundaries were falsely being checked for "end >= boundary", but is now correctly "end > boundary". Please install `0.11.5` for the fix.

ERROR2 is connected to the first one - it just tells you that the logger which runs in each job was killed because of ERROR1. I hope it runs through for you with the new version.

**Comment by 2961461560** [comment] 2020-07-23 09:04
Ok, thank you. I'am trying now
