### ISSUE TITLE
SyntaxError when running BINDetect

### ISSUE THREAD

**Issue by yrmeng** [loosolab/TOBIAS#33] opened 2020-09-28 17:00 UTC
Hi, I am having issues with running BINDetect. The commandline call used is the same as the test data.

`TOBIAS BINDetect --motifs test_data/motifs.jaspar --signals test_data/Bcell_footprints.bw test_data/Tcell_footprints.bw --genome test_data/genome.fa.gz --peaks test_data/merged_peaks_annotated.bed --peak_header test_data/merged_peaks_annotated_header.txt --outdir BINDetect_output --cond_names Bcell Tcell --cores 8`

I also tried with my own data by modifying the code but got the same error. The error message is as below:

Traceback (most recent call last):
  File "/t1-data/user/ymeng/tobias/bin/TOBIAS", line 11, in <module>
    load_entry_point('tobias==0.12.1', 'console_scripts', 'TOBIAS')()
  File "/t1-data/user/ymeng/tobias/lib/python3.5/site-packages/tobias-0.12.1-py3.5-linux-x86_64.egg/tobias/TOBIAS.py", line 149, in main
    module = importlib.import_module(mod_name)  #load specific module
  File "/package/python/3.5.3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/t1-data/user/ymeng/tobias/lib/python3.5/site-packages/tobias-0.12.1-py3.5-linux-x86_64.egg/tobias/tools/bindetect.py", line 42, in <module>
    from tobias.tools.bindetect_functions import *
  File "/t1-data/user/ymeng/tobias/lib/python3.5/site-packages/tobias-0.12.1-py3.5-linux-x86_64.egg/tobias/tools/bindetect_functions.py", line 47, in <module>
    from tobias.utils.motifs import *
  File "/t1-data/user/ymeng/tobias/lib/python3.5/site-packages/tobias-0.12.1-py3.5-linux-x86_64.egg/tobias/utils/motifs.py", line 999
    out_string += f">{self.id}\t{self.name}\n"
                                             ^
SyntaxError: invalid syntax

The version of TOBIAS is 0.12.1 and I am runnig it on linux system.

Thanks in advance!

**Comment by msbentsen** [comment] 2020-09-29 07:35
Hi, thank you for posting the command and error message. I can't reproduce the SyntaxError for 0.12.1, so I am wondering if something might have gone wrong during install? Could you try to uninstall and reinstall? Thanks!

**Comment by yrmeng** [comment] 2020-09-29 14:29
Hi, thanks for your reply. I think I have found a way to solve/ the issue.

I have been using the server provided by the computational centre in our institute, and we usually don't have the privilege to update packaged/libraries. The server has only installed an older version of TOBIAS (0.10.1) so I tried python venv and installed 0.12.1 but got the errors above with BINDetect (other functions worked fine). Reinstalling the packge did not seems to solve the problem.

In the end, I decided to install TOBIAS on my own computer (windows subsystem for ubuntu) where I have more control and after installing the packge with the conda enviroment, it is working well so far (BINDetect runs successfully). I will play around with other functions.

I still don't know what caused the problem when I was using it on the server and the issue seems to be specific to the BINDetect function, but I think you are right that something went wrong during the installation (probably some depedencies were not correctly installed). Thanks again for your advice!

**Comment by msbentsen** [comment] 2020-09-30 10:06
Hi, I am glad you got it solved anyway! I guess there is a conflict between the old/new version, which somehow leads to the error. But since it works in a fresh install, it does not seem to be a problem with TOBIAS itself. I will close this issue, but let me know if you have any other issues.

**Closed by msbentsen** 2020-09-30 10:06 UTC
