### ISSUE TITLE
ClusterMotifs is gone in 0.12.6

### ISSUE THREAD

**Issue by Rosmaninho** [loosolab/TOBIAS#44] opened 2020-11-25 16:24 UTC
As title says... Sorry about all the issues opened...

**Comment by msbentsen** [comment] 2020-11-25 18:03
Are you certain that you have 0.12.6? You can check it with `TOBIAS --version`.

For 0.12.6, with `TOBIAS --help`, I get:
```$ TOBIAS
 ______________________________________________________________________________
|                                                                              |
|                                ~ T O B I A S ~                               |
|                   Transcription factor Occupancy prediction                  |
|                       By Investigation of ATAC-seq Signal                    |
|______________________________________________________________________________|

Usage: TOBIAS <TOOLNAME> [arguments]

Tools for footprinting analysis:
   ATACorrect           Correct reads with regards to Tn5 sequence bias
   ScoreBigwig          Calculate scores such as footprints from cutsites
   BINDetect            Detect TF binding from footprints and motifs

Tools for working with motifs/TFBS:
   TFBScan              Identify positions of TFBS given sequence and motifs
   FormatMotifs         Utility to deal with motif files
   ClusterMotifs        Cluster motifs by similarity
   ScoreBed             Score .bed-file with signal from .bigwig-file(s)

Visualization tools:
   PlotAggregate        Aggregate of .bigwig-signal across TF binding sites
   PlotHeatmap          Heatmap of .bigwig-signal across TF binding sites
   PlotChanges          Plot changes in TF binding across multiple conditions (from BINDetect output)
   PlotTracks           Plot genomic tracks using the svist4get package

Miscellaneous tools:
   DownloadData         Download test data for the TOBIAS tools
   MergePDF             Merge pdf files to one
   MaxPos               Get .bed-positions of highest bigwig signal within .bed-regions
   SubsampleBam         Subsample a .bam-file using samtools
   CreateNetwork        Create TF-gene network from annotated TFBS
   Log2Table            Convert logs from PlotAggregate to tab-delimitered tables of footprint stats
   FilterFragments      Tool for filtering fragments from a .bam-file based on the overlap of reads with .bed-regions

For help on each tool, please run: TOBIAS <TOOLNAME> --help
For version number: TOBIAS --version
```

Which contains ClusterMotifs.

**Comment by Rosmaninho** [comment] 2020-11-26 11:34
I installed it following the instructions on https://github.com/loosolab/TOBIAS/wiki/installation with the TOBIAS_ENV.
Apparently the TOBIAS version it installed is version 0.9.0.

**Comment by msbentsen** [comment] 2020-11-26 12:19
Okay, I can't reproduce that on my end, but I made a small change in the `tobias_env.yaml`, adjusting which might have caused the issue. I'm closing this since the solution was found.

**Closed by msbentsen** 2020-11-26 12:19 UTC

**Comment by charlesfeigin** [comment] 2021-05-03 20:04
Yeah I had the same issue when trying to install using the installation instructions. Conda downloads 0.9.0 instead of the current version
