### ISSUE TITLE
TOBIAS FormatMotifs error

### ISSUE THREAD

**Issue by Knetsy** [loosolab/TOBIAS#25] opened 2020-08-24 09:54 UTC
Hello,

I have installed the TOBIAS snakemake pipeline and run it on the test data. 
Unfortunately, I got an error messages at the "TOBIAS FormatMotifs" step and then TOBIAS stops.

I attach the log file 
[2020-08-24T112429.876842.snakemake.log](https://github.com/loosolab/TOBIAS/files/5117057/2020-08-24T112429.876842.snakemake.log)

Of note, I had difficulties to install the snakemake file using conda as pybigwig and gimmemotifs were not installed properly.
I installed them manually before rerunning the command conda env update -n TOBIAS_ENV --file environments/tobias.yaml but then get many conflicts between installed packages. 

Thanks in advance for your answer and have a nice day!

Deborah

**Comment by msbentsen** [comment] 2020-08-24 11:58
Hi Deborah,

Thank you for the error log - that is very helpful! Could you post the contents of `test_output/logs/format_motifs.log`? The rule format_motifs somehow failed, and the log might give us a hint as to why.

For the installation, there are unfortunately some issues when installing from conda. I sometimes "hack" it by installing the minimal dependencies and then using `pip install TOBIAS` into the environment. It's not an optimal situation though, so I will see if something can be done to the .yaml-file.

Best Mette

**Comment by Knetsy** [comment] 2020-08-24 12:13
Hi Mette,
Thanks for your answer! 
Here is the the contents of [test_output/logs/format_motifs.log](https://github.com/loosolab/TOBIAS/files/5117651/format_motifs.log)

Best,

Deborah

**Comment by msbentsen** [comment] 2020-08-24 13:56
Hi Deborah, the error shows that TOBIAS is not available on the commandline. Maybe TOBIAS was never properly installed, as you also said there were some issues when building the environment? 

Before running the pipeline, you need to activate the environment with `conda activate TOBIAS_ENV`, and check that the TOBIAS tools are available with `TOBIAS --help`.

**Comment by msbentsen** [comment] 2020-08-25 09:03
Okay super, no problem, great that we got a step further :-) The new error happens upon building the [tools.yaml environment](https://github.molgen.mpg.de/loosolab/TOBIAS_snakemake/blob/master/environments/tools.yaml), but I have never seen that error before, so I am also a little lost!

Can you build the environment on its own, meaning outside of the snakemake?
`conda env create -f environments/tools.yaml`

Snakemake basically spins up individual environments for specific tasks, so that the needed packages are available. Somehow, this failed within the snakemake run:
```
CreateCondaEnvironmentException:
Could not create conda environment from /mnt/irisgpfs/users/dgerard/Environment/TOBIAS_snakemake/snakefiles/../environments/tools.yaml:
```
So I am just trying to figure out whether the error is related to snakemake or to conda itself.

**Comment by Knetsy** [comment] 2020-08-25 10:59
Yes it worked, the environment has been created.

**Comment by msbentsen** [comment] 2020-08-25 12:02
Okay, great, then I believe the issue is in the long path to the `.snakemake/conda` packages when building the environment.

Can you try to add `--conda-prefix /tmp` or a shorter path such as `--conda-prefix /mnt/irisgpfs/users/dgerard/conda` to the snakemake call? (e.g. `$ snakemake --configfile example_config.yaml --use-conda --cores 2 --conda-prefix /tmp`)

It seems that some older packages (build with conda-build <= 2) are not allowing paths over 80 characters, so specifying a shorter prefix might help.

**Comment by Knetsy** [comment] 2020-08-25 17:58
It worked! :-) 
Thanks again for your help!

**Comment by msbentsen** [comment] 2020-08-26 06:44
Yay, great! I will close this issue but feel free to reopen should anything else come up :-)

**Closed by msbentsen** 2020-08-26 06:44 UTC
