### ISSUE TITLE
Issues with running TOBIAS BINDetect

### ISSUE THREAD

**Issue by lynnyummy** [loosolab/TOBIAS#30] opened 2020-09-18 11:25 UTC
Hi, I am trying to run TOBIAS to analysis my time-series ATAC-seq data, it ran well with ATACorrect and FootprintScores, but reported some errors in BINDetect step.  In short A. it could not write the excel file,  B. It cannot find ( or generate?) the file in beds folder and png result. The following are the detailed explanations, I am so sorry there are lots of issues. Could you please help to check these errors? I am very much appreciated to your kind helps! Thank you very much!!

1. I wanted to use it predict all the motifs' binding in a single condition (merge all the time points), here is the command
 `TOBIAS BINDetect --motifs all.motifs --signals all_correct_merged_footprints.bw --genome genome.fa --peaks all_peaks.bed --outdir all_motifs_corrected_merged_output --cores 6`
It reported some errors,
(1)`Error writing excelfile for TF 2-TTCGTTTGGAAA_TTTCCAAACGAA. Exception was: This sheet is too large! Your sheet size is: 1580281, 13 Max sheet size is: 1048576, 16384` (lots of this type of errors.)
(2) `Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.`
(3)  `FileNotFoundError: [Errno 2] No such file or directory: '/tobias/all_motifs_corrected_merged_output/_/beds/_.tmp'`

2.  I wanted to use it to predict all the motifs' binding for a timeline, here is the command,
`TOBIAS BINDetect --motifs all.motifs --signals 1_correct_footprints.bw _2_correct_footprints.bw 3_correct_footprints.bw 4_correct_footprints.bw --genome  genome.fa --peaks all_peaks.bed --outdir allmotifs_time_series_output --naming id --time-series --cores 6`
It still reported error,
`with open(logo_filenames[motif.prefix], "rb") as png:
FileNotFoundError: [Errno 2] No such file or directory: 'allmotifs_time_series_output/.png'`

3. I wanted to use it to predict one motif's binding in a single condition (merge all the time points) and in a timeline condition respectively, it ran normally for the single condition, while still reported error in the timeline condition. The commands are,

`TOBIAS BINDetect --motifs known1.motif --signals all_correct_merged_footprints.bw --genome genome.fa --peaks all_peaks.bed --outdir known1_corrected_merged_output --cores 4` 

`TOBIAS BINDetect --motifs known1.motif --signals 1_correct_footprints.bw _2_correct_footprints.bw 3_correct_footprints.bw 4_correct_footprints.bw --genome  genome.fa --peaks all_peaks.bed --outdir known1_motif_time_series_output --naming id --time-series --cores 6`
The one motif in timeline condition reported the error,
`File ".conda/envs/biotools/lib/python3.6/site-packages/tobias/tools/bindetect.py", line 261, in run_bindetect with open(logo_filenames[motif.prefix], "rb") as png:
FileNotFoundError: [Errno 2] No such file or directory: '/known1_motif_time_series_output/.png'`

**Comment by msbentsen** [comment] 2020-09-18 11:41
Hi! Can you share a subset of your `all.motifs` and `known1.motif` files? It seems that some of the motifs might have empty names, and that BINDetect somehow fails to read and write the output files for these. This would definitely be a bug!

With regards to the first errors of excel-writing - as the error says, the python excelwriter tries to save a sheet of 1,5million lines, and that is over the limit. I unfortunately cannot change that. It is actually just a warning though (I will change it from ERROR -> WARNING), so it will not influence the computation, and the results are still available in full within the .txt-files. I guess your `--peaks` span a large portion of the genome?

**Comment by lynnyummy** [comment] 2020-09-18 12:23
Hi! Thanks for your reply! I also wondered if it is the motifs error, cause they are from the HOMER results....They look like this,
part of all.motifs.
`>ACTTTCACTTTC   PRDM1(Zf)/Hela-PRDM1-ChIP-Seq(GSE31477)/Homer   7.912770        -17.627036      0       T:1883.0(4.31%),B:1660.2(3.80%),P:1e-7
0.700   0.111   0.133   0.056
0.109   0.787   0.053   0.051
0.072   0.026   0.003   0.899
0.007   0.082   0.031   0.880
0.014   0.002   0.014   0.970
0.008   0.941   0.002   0.049
0.535   0.151   0.064   0.250
0.035   0.873   0.027   0.065
0.022   0.152   0.001   0.825
0.112   0.126   0.184   0.578
0.208   0.160   0.135   0.496
0.145   0.435   0.163   0.257
>ACAGGAAGTG     ETS1(ETS)/Jurkat-ETS1-ChIP-Seq(GSE17954)/Homer  6.525370        -17.504460      0       T:2592.0(5.94%),B:2332.7(5.34%),P:1e-7
0.539   0.088   0.332   0.041
0.093   0.722   0.181   0.004
0.719   0.272   0.008   0.001
0.001   0.001   0.997   0.001
0.001   0.001   0.997   0.001
0.997   0.001   0.001   0.001
0.869   0.001   0.001   0.129
0.116   0.001   0.882   0.001
0.024   0.137   0.001   0.838
0.112   0.128   0.654   0.106`

and known1.motif
`>TAATCCCN       Pitx1(Homeobox)/Chicken-Pitx1-ChIP-Seq(GSE38910)/Homer  4.695187        -40.057176      0       T:22934.0(52.53%),B:22043.9(50.48%),P:1e-17
0.194   0.016   0.024   0.766
0.860   0.001   0.095   0.044
0.969   0.002   0.004   0.025
0.135   0.042   0.214   0.609
0.054   0.671   0.078   0.197
0.044   0.839   0.006   0.111
0.191   0.477   0.060   0.273
0.187   0.219   0.314   0.280`

They are not in either PFM, JASPAR or MEME format.. but because it ran normally in the one motif one condition so I just continued the analysis...
Please let me know if I need and how can I adjust the motif format.. Thank you very much!

And yes I can see the result from the txt-files. Thank you!
Yes the bed of peaks is a big one span the whole genome...Would it be an issue while processing the analysis? Should I do anything about this? 

Thanks for your kind helps!

**Comment by lynnyummy** [comment] 2020-09-19 01:13
> Hi! Can you share a subset of your `all.motifs` and `known1.motif` files? It seems that some of the motifs might have empty names, and that BINDetect somehow fails to read and write the output files for these. This would definitely be a bug!
> 
> With regards to the first errors of excel-writing - as the error says, the python excelwriter tries to save a sheet of 1,5million lines, and that is over the limit. I unfortunately cannot change that. It is actually just a warning though (I will change it from ERROR -> WARNING), so it will not influence the computation, and the results are still available in full within the .txt-files. I guess your `--peaks` span a large portion of the genome?

Hi! I read about the MEME motif format, I am wondering if I can adjust the HOMER motif format to MEME format manually? Like this,

MEME version 4

MOTIF Pitx1
letter-probability matrix: alength= 4 w= 8 nsites= 20 E= 0
0.194   0.016   0.024   0.766
0.860   0.001   0.095   0.044
0.969   0.002   0.004   0.025
0.135   0.042   0.214   0.609
0.054   0.671   0.078   0.197
0.044   0.839   0.006   0.111
0.191   0.477   0.060   0.273
0.187   0.219   0.314   0.280


Is it accepted by the BINDetect? If it is doable, I think I can change all the HOMER motifs format to adapt to the MEME format. Please let me know if I can try to solve this issue in this way. Thank you very much!

**Comment by lynnyummy** [comment] 2020-09-20 16:15
Hi! I finally changed the HOMER motif format to the MEME format, and it works!  Now I would continue the analysis, but I cannot find the example file from https://github.com/loosolab/TOBIAS/blob/master/test_data/motif2gene_mapping.txt. Could you please share the example of doing `CreateNetwork `? Thank you very much!

**Comment by msbentsen** [comment] 2020-09-21 07:32
Hi, I am glad that you got it solved! You are right that BINDetect does not support HOMER motifs yet, but I will put it on my list of improvements for the future. Thank you for the example motifs.

For the peak-files, I recommend using peak-files obtained by regular peak-calling (using e.g. MACS2), as this is what the algorithm was made for. Because footprints can only be estimated in regions of higher signal (e.g. peaks), we anyway assume the majority of the genome to have footprint scores of 0 - so you are saving a lot of computation by having a smaller `--peaks` set.

And whoops, that is a link leftover from when the test-data was in the repository - that is my fault. Please run these commands (also seen on https://github.com/loosolab/TOBIAS/wiki/test-data):
```
$ TOBIAS DownloadData --bucket data-tobias-2020
$ mv data-tobias-2020/ test_data/
```
To download the test-data (the file will be in the test_data folder).  Hope this works out for you!

**Comment by lynnyummy** [comment] 2020-09-21 21:19
> Hi, I am glad that you got it solved! You are right that BINDetect does not support HOMER motifs yet, but I will put it on my list of improvements for the future. Thank you for the example motifs.
> 
> For the peak-files, I recommend using peak-files obtained by regular peak-calling (using e.g. MACS2), as this is what the algorithm was made for. Because footprints can only be estimated in regions of higher signal (e.g. peaks), we anyway assume the majority of the genome to have footprint scores of 0 - so you are saving a lot of computation by having a smaller `--peaks` set.
> 
> And whoops, that is a link leftover from when the test-data was in the repository - that is my fault. Please run these commands (also seen on https://github.com/loosolab/TOBIAS/wiki/test-data):
> 
> ```
> $ TOBIAS DownloadData --bucket data-tobias-2020
> $ mv data-tobias-2020/ test_data/
> ```
> 
> To download the test-data (the file will be in the test_data folder). Hope this works out for you!

Hi ! Thanks for your reply and update, I will try the new data link. Finger cross~

**Comment by gtrichard** [comment] 2020-09-22 09:45
Hello, I also got the same following issue with BINDetect during the `Processing scanned TFBS individually` step:

```
(2) Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
```

It crashed after `AbdA_Cell_FBgn0000014`.

I am using FAIRE-seq signal though (Log2ratio bigwig files of FAIRE DNA / Input, like ChIP-seq data), but the log2ratio computation step in TOBIAS worked well.

I attached the motifs file (meme format, txt extension to allow upload on github).
[TFs.meme.txt](https://github.com/loosolab/TOBIAS/files/5260453/TFs.meme.txt)

**Comment by lynnyummy** [comment] 2020-09-22 20:00
> Hello, I also got the same following issue with BINDetect during the `Processing scanned TFBS individually` step:
> 
> ```
> (2) Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
> ```
> 
> It crashed after `AbdA_Cell_FBgn0000014`. Although it's the first motif of the motif file, many other motifs worked (268 worked).
> 
> I am using FAIRE-seq signal though (Log2ratio bigwig files of FAIRE DNA / Input, like ChIP-seq data), but the log2ratio computation step in TOBIAS worked well.
> 
> I attached the motifs file (from _D. melanogaster_, meme format, txt extension to allow upload on github).
> [TFs.meme.txt](https://github.com/loosolab/TOBIAS/files/5260453/TFs.meme.txt)

Hi, I didn't get this error after I changed the motifs format, I don't know if it is because of "URL http://pgfe.umassmed.edu/TFDBS/TFdetails.php?FlybaseID=FBgn0000028" in the file? Maybe you can have a try? Sorry I am not very familiar with this!

**Comment by msbentsen** [comment] 2020-09-23 07:30
> 
> 
> Hello, I also got the same following issue with BINDetect during the `Processing scanned TFBS individually` step:
> 
> ```
> (2) Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
> ```
> 
> It crashed after `AbdA_Cell_FBgn0000014`. Although it's the first motif of the motif file, many other motifs worked (268 worked).
> 
> I am using FAIRE-seq signal though (Log2ratio bigwig files of FAIRE DNA / Input, like ChIP-seq data), but the log2ratio computation step in TOBIAS worked well.
> 
> I attached the motifs file (from _D. melanogaster_, meme format, txt extension to allow upload on github).
> [TFs.meme.txt](https://github.com/loosolab/TOBIAS/files/5260453/TFs.meme.txt)

Hi, I cannot reproduce the error with your motifs - it is not an error with the motif format at least. The `Multiprocessing logger lost connection to queue` error just signifies that there was an error from an individual job in the multiprocessing queue, so there should have been another error which caused this. Can you send the full log? Thanks!

**Comment by lynnyummy** [comment] 2020-09-23 09:09
> > Hello, I also got the same following issue with BINDetect during the `Processing scanned TFBS individually` step:
> > ```
> > (2) Multiprocessing logger lost connection to queue - probably due to an error raised from a child process.
> > ```
> > 
> > 
> > It crashed after `AbdA_Cell_FBgn0000014`. Although it's the first motif of the motif file, many other motifs worked (268 worked).
> > I am using FAIRE-seq signal though (Log2ratio bigwig files of FAIRE DNA / Input, like ChIP-seq data), but the log2ratio computation step in TOBIAS worked well.
> > I attached the motifs file (from _D. melanogaster_, meme format, txt extension to allow upload on github).
> > [TFs.meme.txt](https://github.com/loosolab/TOBIAS/files/5260453/TFs.meme.txt)
> 
> Hi, I cannot reproduce the error with your motifs - it is not an error with the motif format at least. The `Multiprocessing logger lost connection to queue` error just signifies that there was an error from an individual job in the multiprocessing queue, so there should have been another error which caused this. Can you send the full log? Thanks!

Sorry I have already deleted those log files(my space is full...).. I wonder if it is the issue of the `MOTIF FBgn0000014 AbdA_Cell`? Maybe you can try `MOTIF 1 AbdA_Cell`?

**Comment by msbentsen** [comment] 2020-09-23 10:20
> Sorry I have already deleted those log files(my space is full...).. I wonder if it is the issue of the `MOTIF FBgn0000014 AbdA_Cell`? Maybe you can try `MOTIF 1 AbdA_Cell`?

The request for logfiles was meant for @gtrichard - sorry for the confusion! I appreciate that you are trying to help - but as I already wrote earlier, there is nothing wrong with the motifs in [TFs.meme.txt](https://github.com/loosolab/TOBIAS/files/5260453/TFs.meme.txt). I think the two issues are unrelated (although they might produce the same error message), so you can safely disregard any of the further discussions :-)

**Comment by gtrichard** [comment] 2020-09-23 13:07
Here's the full log (err and out)

TOBIAS cannot find a tmp file generated by TOBIAS. It's not a write permission nor a storage quota issue.

[grichard.1522399.out.txt](https://github.com/loosolab/TOBIAS/files/5268268/grichard.1522399.out.txt)
[grichard.1522399.err.txt](https://github.com/loosolab/TOBIAS/files/5268269/grichard.1522399.err.txt)

**Comment by msbentsen** [comment] 2020-09-24 07:42
I would have done the same thing, as the error pointed to the same issue! But now I think they are actually separate - so I have created an issue specifically for this. I am closing this one as I think the initial HOMER-motif issue was solved.

**Closed by msbentsen** 2020-09-24 07:42 UTC
Labels: enhancement
