### ISSUE TITLE
BINDetect ValueError

### ISSUE THREAD

**Issue by parmejohn** [loosolab/TOBIAS#34] opened 2020-10-15 18:28 UTC
Hi @msbentsen,
I have tried using TOBIAS v0.12.1 BINDetect across 25 samples with this code,

`TOBIAS BINDetect --signals example/*_corrected_footprints.bw --motifs example/motifs --genome example/fasta --peaks example/bed --skip-excel --outdir output/bindetect --verbosity 4 --cores 25`

and I keep running into this error

```
/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect.py:388: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  figure_pdf.savefig(fig, bbox_inches='tight')
Traceback (most recent call last):
  File "/home/jopham/anaconda3/envs/TOBIAS/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/tobias/tools/bindetect.py", line 412, in r
un_bindetect
    gmm.fit(np.log(bg_values).reshape(-1, 1))
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 53, in _check_X
    ensure_min_samples=ensure_min_samples)
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
return f(**kwargs)
  File "/home/jopham/anaconda3/envs/TOBIAS/lib/python3.7/site-packages/sklearn/utils/validation.py", line 653, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 2 is required.
```

I have checked that the *_corrected_footprints.bw files have information in them. Also, I have the log file if you would like it as well.

Sorry about the formatting of the error, this is my first time commenting an issue on github and thanks for helping in advance!

**Comment by msbentsen** [comment] 2020-10-16 08:03
Hi,
Thank you for writing the call and error - the formatting is perfect, no worries :-) Yes, could you attach the logfile as well? 
That would be very helpful, thanks!

**Comment by parmejohn** [comment] 2020-10-16 21:34
I have had to edit the log file due to some data restrictions on my end, but I hope this log file would be enough.

[bindetect_log_edited.txt](https://github.com/loosolab/TOBIAS/files/5394386/bindetect_log_edited.txt)

**Comment by msbentsen** [comment] 2020-10-20 12:37
Thank you for including the logfile. The problem seems to be that the sampled background values are being reduced to an empty array - either because the values are 0, or because they are all of equal value. However, since you say they contain values, I am not quite sure what is going on. Is it possible for you to send me one of the bigwigs for testing? Sorry for the inconvenience!

**Comment by parmejohn** [comment] 2020-10-23 21:12
Sorry for replying so late, I was checking with my supervisor to see if it was ok, and am sending the files through a OneDrive link from email, since the files are too large. Thanks again for all the help!

Also, I tested the corrected .bw of the same set of cells on a different region and the output turned out fine. I have also used the same in this error .bed file for a different analysis so I am not too what is happening either. I will also send over the bed file that I have used as well.

**Comment by blairperry** [comment] 2020-10-28 12:41
I am running into the same error when running the Snakemake pipeline using the example config file and example files. This is with TOBIAS v0.12.3.

**Comment by msbentsen** [comment] 2020-10-29 09:08
> 
> 
> I am running into the same error when running the Snakemake pipeline using the example config file and example files. This is with TOBIAS v0.12.3.

I can reproduce this for the test data - definitely a bug, but maybe due to a change in functionality of a dependency (e.g. numpy or scipy), but I am not 100% sure yet. I am having a look at it now!

**Comment by blairperry** [comment] 2020-10-30 15:47
Despite the error when running the example data, BINDetect worked perfectly when I plugged in my own data and ran commands manually instead of within the snakemake pipeline. I'm not sure if this is helpful, but figured it might help narrow in on the issue.

**Comment by msbentsen** [comment] 2020-11-02 12:09
Thank you for all of the information @parmejohn and @blairperry :-) I narrowed it down to the across-condition normalization within BINDetect, which failed for some specific outlier cases, thereby introducing NA's into the data. I made some changes in `tobias 0.12.4` to make this more robust. The normalization is a little different, so for the sake of comparison, please update and rerun analysis (even those which might have run through with the old version). 

I will close this issue, but thank you for your inputs, and please reopen if you encounter any other issues!

**Closed by msbentsen** 2020-11-02 12:09 UTC
Labels: bug
