### ISSUE TITLE
Run BINDetect error

### ISSUE THREAD

**Issue by tzhu-bio** [loosolab/TOBIAS#107] opened 2021-12-06 02:00 UTC
This is my meme file:
[oryza_sativa.txt](https://github.com/loosolab/TOBIAS/files/7657390/oryza_sativa.txt)

I ran BINDetect  with the above meme file and got this error (The program is stuck here)
![image](https://user-images.githubusercontent.com/54537420/144775387-b28bd9cc-b885-4934-b644-be80bb7d53b8.png)

**Comment by msbentsen** [comment] 2021-12-06 10:44
Hi @tzhu-bio,
Thank you for your issue and for attaching the input motifs! I could reproduce the error with your file, and it occurred because `nsites= 1` is set for each motif, but BINDetect expected it to be set to the number of sites used to create the motif - and this was a bug! I made a fix for version 0.13.1 (https://github.com/loosolab/TOBIAS/commit/a1c8633f878ab60f34d7aa2b00ec2ad06863bc85), so please have a look if this fixes the issue. Thanks!

**Comment by tzhu-bio** [comment] 2021-12-06 10:51
Thanks for your reply. Is there an easy way to reinstall this package?

**Comment by msbentsen** [comment] 2021-12-06 10:54
I just added it to PyPI, so you should be able to do directly do `pip install tobias==0.13.1` or you can install directly from github as shown [here](https://github.com/loosolab/TOBIAS/wiki/installation).

**Comment by tzhu-bio** [comment] 2021-12-06 10:55
Thank you very much!

**Comment by msbentsen** [comment] 2021-12-06 10:58
You're welcome! I am closing this, but feel free to reopen in case of issues :-)

**Closed by msbentsen** 2021-12-06 10:58 UTC
Labels: bug
